/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Warehouse;

import Business.OrderPackage.Batch;
import Business.DrugPackage.Drug;
import Business.EnterprisePackage.ManufacturerEnterprise;
import Business.OrderPackage.Order;
import Business.OrderPackage.Packet;
import Business.UserAccountPackage.UserAccount;
import Business.EnterprisePackage.WarehouseEnterprise;
import Business.WorkRequestPackage.FromSalesWorkRequest;
import Business.WorkRequestPackage.FromWareHouseWorkRequest;
import Business.WorkRequestPackage.ToInventoryWorkRequest;
import Business.WorkRequestPackage.WorkRequest;
import UserInterface.Hospital.OrderBatchDetailsJPanel;
import UserInterface.Hospital.OrderDetailsJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.util.Calendar;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rishabh
 */
public class ViewInventoryManuAllOrdersJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount userAccount;
    WarehouseEnterprise wareHouseEnterprise;

    /**
     * Creates new form ViewWareHouseAllOrdersJPanel
     */
    public ViewInventoryManuAllOrdersJPanel(JPanel j, WarehouseEnterprise wh, UserAccount u) {
        initComponents();
        userProcessContainer = j;
        wareHouseEnterprise = wh;
        userAccount = u;

        Calendar currentDate = Calendar.getInstance();
        SimpleDateFormat formatter = new SimpleDateFormat("MMM/dd/yyyy");
        String dateNow = formatter.format(currentDate.getTime());
        lblDate.setText(dateNow);

        Refresh();
    }

    public void Refresh() {

        int rowCount1 = ordersPlacedJTable.getRowCount();

        for (int i = rowCount1 - 1; i >= 0; i--) {
            ((DefaultTableModel) ordersPlacedJTable.getModel()).removeRow(i);
        }

        int rowCount = ordersReceivedJTable.getRowCount();

        for (int i = rowCount - 1; i >= 0; i--) {
            ((DefaultTableModel) ordersReceivedJTable.getModel()).removeRow(i);
        }

        for (WorkRequest wr : wareHouseEnterprise.getWarehouseManagerOrganization().getWorkQueue().getWorkRequestQueue()) {

            if(wr instanceof FromWareHouseWorkRequest)
            {
            Object row[] = new Object[7];
            
            row[0] = (FromWareHouseWorkRequest) wr;
            row[1] = wr.getSender();
            row[2] = wr.getReceiver();
            row[3] = wr.getStatus();
            row[4] = (((FromWareHouseWorkRequest) wr).getManufacturerEnterprise());
            row[5] = wr.getSendingDate();
            row[6] = wr.getReceivingDate();
            ((DefaultTableModel) ordersPlacedJTable.getModel()).addRow(row);
            }
        }

        for (WorkRequest wr : (wareHouseEnterprise.getInventoryManagerOrganization().getWorkQueue().getWorkRequestQueue())) {
            if(wr instanceof ToInventoryWorkRequest)
            {
            Object row[] = new Object[8];
            row[0] = (ToInventoryWorkRequest) wr;
            row[1] = ((ToInventoryWorkRequest) wr).getBatch();
            row[2] = wr.getSender();
            row[3] = wr.getReceiver();
            row[4] = wr.getStatus();
            row[5] = ((ToInventoryWorkRequest) wr).getManufacturerEnterprise();
            row[6] = wr.getSendingDate();
            row[7] = wr.getReceivingDate();

            ((DefaultTableModel) ordersReceivedJTable.getModel()).addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAddToInventory = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordersReceivedJTable = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ordersPlacedJTable = new javax.swing.JTable();
        lblDate = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnViewDetailsOR = new javax.swing.JButton();
        btnViewDetailsAPO = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Order Received From Manufacturer");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 340, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1000, 10));

        btnAddToInventory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddToInventory.setText("Add To Inventory");
        btnAddToInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToInventoryActionPerformed(evt);
            }
        });
        add(btnAddToInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, -1, 30));

        ordersReceivedJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "OrderID", "Batch ID", "Sender", "Receiver", "Status", "Manufacturer Name", "Sending Date", "Receiving Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ordersReceivedJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 970, 130));

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 80, -1, -1));

        ordersPlacedJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "OrderID", "Sender", "Receiver", "Status", "Manufacturer Name", "SendingDate", "Receiving Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ordersPlacedJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 970, 120));

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 110, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Inventory Manager workarea");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 320, -1));

        btnViewDetailsOR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewDetailsOR.setText("View Details");
        btnViewDetailsOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsORActionPerformed(evt);
            }
        });
        add(btnViewDetailsOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 460, -1, -1));

        btnViewDetailsAPO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewDetailsAPO.setText("View Details");
        btnViewDetailsAPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsAPOActionPerformed(evt);
            }
        });
        add(btnViewDetailsAPO, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("All Orders Placed To Manufacturer");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 330, -1));

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddToInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToInventoryActionPerformed

        int selectedRow = ordersReceivedJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select row to Add it to Inventory");
            return;
        }

        WorkRequest wr1 = (WorkRequest) ordersReceivedJTable.getValueAt(selectedRow, 0);

        if (((ToInventoryWorkRequest) wr1).getStatus().equals(WorkRequest.Done)) {
            JOptionPane.showMessageDialog(null, "Already Added To Inventory");
            return;
        }

        wr1.setStatus(WorkRequest.Done);
        wr1.setReceiver(userAccount);
        wr1.setReceivingDate(lblDate.getText());

        for (WorkRequest workRequest : wareHouseEnterprise.getWarehouseManagerOrganization().getWorkQueue().getWorkRequestQueue()) {
            if(workRequest instanceof FromWareHouseWorkRequest )
            {
            if (((FromWareHouseWorkRequest) workRequest).getOrder().getOrderID().equals(((ToInventoryWorkRequest) wr1).getOrder().getOrderID())) {
                workRequest.setStatus(WorkRequest.Done);
            }}
        }

        ManufacturerEnterprise manufacturerEnterprise = ((ToInventoryWorkRequest) wr1).getManufacturerEnterprise();
        for (WorkRequest wr : manufacturerEnterprise.getSalesManagerOrganization().getWorkQueue().getWorkRequestQueue()) {
            if(wr instanceof FromSalesWorkRequest )
            {
            if ((((FromSalesWorkRequest) wr).getOrder().getOrderID()).equals(((ToInventoryWorkRequest) wr1).getOrder().getOrderID())) {
                wr.setReceiver(userAccount);
                wr.setStatus(WorkRequest.Done);
                wr.setReceivingDate(lblDate.getText());
            }
            }
        }

        for (Packet packet : ((ToInventoryWorkRequest) wr1).getBatch().getPacketList()) {

            Drug drug = new Drug();
            drug.setDrugName(packet.getDrug().getDrugName());
            drug.setExpiryDate(packet.getDrug().getExpiryDate());
            drug.setManufacturerName(packet.getDrug().getManufacturerName());
            drug.setNoOfUnits(packet.getDrug().getNoOfUnits());
            drug.setUnitPrice(packet.getDrug().getUnitPrice());

            wareHouseEnterprise.getDrugDirectory().getDrugDirectory().add(drug);
        }


        Refresh();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddToInventoryActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed

        Refresh();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnViewDetailsORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsORActionPerformed

        int selectedRow = ordersReceivedJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select Row to view details");
            return;
        }

        WorkRequest workRequest = (WorkRequest) ordersReceivedJTable.getValueAt(selectedRow, 0);
        Order order = ((ToInventoryWorkRequest) workRequest).getOrder();
        Batch batch = ((ToInventoryWorkRequest) workRequest).getBatch();
        OrderBatchDetailsJPanel panel = new OrderBatchDetailsJPanel(userProcessContainer, order, batch);
        userProcessContainer.add("warehouse Orders Received from Manufacturer details", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewDetailsORActionPerformed

    private void btnViewDetailsAPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsAPOActionPerformed

        int selectedRow = ordersPlacedJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select Row to view details");
            return;
        }

        WorkRequest workRequest = (WorkRequest) ordersPlacedJTable.getValueAt(selectedRow, 0);
        Order order = ((FromWareHouseWorkRequest) workRequest).getOrder();
        OrderDetailsJPanel panel = new OrderDetailsJPanel(userProcessContainer, order);
        userProcessContainer.add("warehouse Orders placed to manufacturer details", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewDetailsAPOActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnAddToInventory;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnViewDetailsAPO;
    private javax.swing.JButton btnViewDetailsOR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JTable ordersPlacedJTable;
    private javax.swing.JTable ordersReceivedJTable;
    // End of variables declaration//GEN-END:variables
}
