/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Warehouse;

import Business.EcoSystem;
import Business.EnterprisePackage.HospitalEnterprise;
import Business.OrderPackage.Order;
import Business.UserAccountPackage.UserAccount;
import Business.EnterprisePackage.WarehouseEnterprise;
import Business.WorkRequestPackage.FromDispenserWorkRequest;
import Business.WorkRequestPackage.FromWareHouseWorkRequest;
import Business.WorkRequestPackage.ToWareHouseWorkRequest;
import Business.WorkRequestPackage.WorkRequest;
import UserInterface.Hospital.OrderDetailsJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.util.Calendar;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rishabh
 */
public class ViewWarehouseAllOrdersJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount userAccount;
    WarehouseEnterprise warehouseEnterprise;
    EcoSystem ecoSystem;

    /**
     * Creates new form ViewWareHouseAllOrdersJPanel
     */
    public ViewWarehouseAllOrdersJPanel(JPanel userProcessContainer, WarehouseEnterprise warehouseEnterprise, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.warehouseEnterprise = warehouseEnterprise;
        this.userAccount = userAccount;
        this.ecoSystem=EcoSystem.getInstance();

        Calendar currentDate = Calendar.getInstance();
        SimpleDateFormat formatter = new SimpleDateFormat("MMM/dd/yyyy");
        String dateNow = formatter.format(currentDate.getTime());
        lblDate.setText(dateNow);

        Refresh();
    }

    public void Refresh() {

        int rowCount1 = tblOrdersPlaced.getRowCount();

        for (int i = rowCount1 - 1; i >= 0; i--) {
            ((DefaultTableModel) tblOrdersPlaced.getModel()).removeRow(i);
        }

        int rowCount = tblOrdersReceived.getRowCount();

        for (int i = rowCount - 1; i >= 0; i--) {
            ((DefaultTableModel) tblOrdersReceived.getModel()).removeRow(i);
        }

        for (WorkRequest wr : warehouseEnterprise.getWarehouseManagerOrganization().getWorkQueue().getWorkRequestQueue()) {

            if(wr instanceof FromWareHouseWorkRequest)
            {
            Object row[] = new Object[7];
            row[0] = (FromWareHouseWorkRequest) wr;
            row[1] = wr.getSender();
            row[2] = wr.getReceiver();
            row[3] = wr.getStatus();
            row[4] = (((FromWareHouseWorkRequest) wr).getManufacturerEnterprise());
            row[5] = wr.getSendingDate();
            row[6] = wr.getReceivingDate();
            ((DefaultTableModel) tblOrdersPlaced.getModel()).addRow(row);
            }
        }

        for (WorkRequest wr : (warehouseEnterprise.getWarehouseManagerOrganization().getWorkQueue().getWorkRequestQueue())) {
            
            if(wr instanceof ToWareHouseWorkRequest)
            {
            Object row[] = new Object[7];
            row[0] = (ToWareHouseWorkRequest) wr;
            row[1] = wr.getSender();
            row[2] = wr.getReceiver();
            row[3] = wr.getStatus();
            row[4] = ((ToWareHouseWorkRequest) wr).getHospitalEnterprise();
            row[5] = wr.getSendingDate();
            row[6] = wr.getReceivingDate();

            ((DefaultTableModel) tblOrdersReceived.getModel()).addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAssignToMe = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrdersReceived = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrdersPlaced = new javax.swing.JTable();
        lblDate = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPlaceOrder = new javax.swing.JButton();
        btnViewDetailsOR = new javax.swing.JButton();
        btnViewDetailsAPO = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Order Received From Hospitals");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 280, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1000, 10));

        btnAssignToMe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAssignToMe.setText("Assign To Me");
        btnAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToMeActionPerformed(evt);
            }
        });
        add(btnAssignToMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, -1, 30));

        tblOrdersReceived.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "OrderID", "Sender", "Receiver", "Status", "Hospital Name", "Sending Date", "Receiving Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrdersReceived);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 970, 130));

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 80, -1, -1));

        tblOrdersPlaced.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "OrderID", "Sender", "Receiver", "Status", "Manufacturer Name", "SendingDate", "Receiving Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblOrdersPlaced);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 980, 140));

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 110, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("WareHouse Manager workarea");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 320, -1));

        btnPlaceOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPlaceOrder.setText("Place An Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });
        add(btnPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, -1, 30));

        btnViewDetailsOR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewDetailsOR.setText("View Details");
        btnViewDetailsOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsORActionPerformed(evt);
            }
        });
        add(btnViewDetailsOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 490, -1, -1));

        btnViewDetailsAPO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewDetailsAPO.setText("View Details");
        btnViewDetailsAPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsAPOActionPerformed(evt);
            }
        });
        add(btnViewDetailsAPO, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("All Orders Placed To Manufacturer");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 330, -1));

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToMeActionPerformed

        int selectedRow = tblOrdersReceived.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "select row");
            return;
        }

        WorkRequest wr1 = (WorkRequest) tblOrdersReceived.getValueAt(selectedRow, 0);

        if (((ToWareHouseWorkRequest) wr1).getStatus().equals(WorkRequest.Recieve) || ((ToWareHouseWorkRequest) wr1).getStatus().equals(WorkRequest.Done)) {
            JOptionPane.showMessageDialog(null, "Work is done already");
            return;
        }

        wr1.setStatus(WorkRequest.Recieve);
        wr1.setReceiver(userAccount);
        wr1.setReceivingDate(lblDate.getText());

        HospitalEnterprise hospitalEnterprise = ((ToWareHouseWorkRequest) wr1).getHospitalEnterprise();
        for (WorkRequest wr : hospitalEnterprise.getDispenserManagerOrganization().getWorkQueue().getWorkRequestQueue()) {
            if(wr instanceof FromDispenserWorkRequest)
            {
            if ((((FromDispenserWorkRequest) wr).getOrder().getOrderID()).equals(((ToWareHouseWorkRequest) wr1).getOrder().getOrderID())) {
                wr.setReceiver(userAccount);
                wr.setStatus(WorkRequest.Sent);
                wr.setReceivingDate(lblDate.getText());
            }
        }
        }


        Refresh();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAssignToMeActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed

        Refresh();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnViewDetailsORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsORActionPerformed

        int selectedRow = tblOrdersReceived.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select Row to view details");
            return;
        }

        WorkRequest workRequest = (WorkRequest) tblOrdersReceived.getValueAt(selectedRow, 0);
        Order order = ((ToWareHouseWorkRequest) workRequest).getOrder();
        OrderDetailsJPanel panel = new OrderDetailsJPanel(userProcessContainer, order);
        userProcessContainer.add("warehouse Orders Received details", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewDetailsORActionPerformed

    private void btnViewDetailsAPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsAPOActionPerformed

        int selectedRow = tblOrdersPlaced.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select Row to view details");
            return;
        }

        WorkRequest workRequest = (WorkRequest) tblOrdersPlaced.getValueAt(selectedRow, 0);
        Order order = ((FromWareHouseWorkRequest) workRequest).getOrder();
        OrderDetailsJPanel panel = new OrderDetailsJPanel(userProcessContainer, order);
        userProcessContainer.add("warehouse Orders placed details", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewDetailsAPOActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed

        PlaceOrderToSalesManagerJPanel panel = new PlaceOrderToSalesManagerJPanel(userProcessContainer, warehouseEnterprise, userAccount,ecoSystem);
        userProcessContainer.add("place order to sales manager", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnAssignToMe;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnViewDetailsAPO;
    private javax.swing.JButton btnViewDetailsOR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JTable tblOrdersPlaced;
    private javax.swing.JTable tblOrdersReceived;
    // End of variables declaration//GEN-END:variables
}
