/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Warehouse;

import Business.DrugPackage.Drug;
import Business.EcoSystem;
import Business.EnterprisePackage.Enterprise;
import Business.UserAccountPackage.UserAccount;
import Business.EnterprisePackage.WarehouseEnterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rishabh
 */
public class WareHouseManagerJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount userAccount;
    WarehouseEnterprise warehouseEnterprise;
    EcoSystem ecoSystem;

    /**
     * Creates new form WareHouseManagerJPanel
     */
    public WareHouseManagerJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount account, EcoSystem business) {
        initComponents();
        this.ecoSystem = business;
        this.userProcessContainer = userProcessContainer;
        this.warehouseEnterprise = (WarehouseEnterprise) enterprise;
        this.userAccount = account;

        lblName.setText("WareHouse Manager Name is : " + account.getEmployee().getFirstName());
        
        
        Refresh();
    }

    public void Refresh() {
        int rowConut = tblDrugDirectory.getRowCount();
        DefaultTableModel dtm=(DefaultTableModel)tblDrugDirectory.getModel();
        for (int i = rowConut - 1; i >= 0; i--) {
           dtm.removeRow(i);
        }

        for (Drug drug : warehouseEnterprise.getDrugDirectory().getDrugDirectory()) {
            Object row[] = new Object[6];
            row[0] = drug.getDrugId();
            row[1] = drug.getDrugName();
            row[2] = drug.getExpiryDate();
            row[3] = drug.getManufacturerName();
            row[4] = drug.getNoOfUnits();
            row[5] = drug.getUnitPrice();

            if (!(drug.getNoOfUnits()== 0)) {
                ((DefaultTableModel) tblDrugDirectory.getModel()).addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDrugDirectory = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnPlaceOrder = new javax.swing.JButton();
        btnViewAllOrders = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        lblCountryState = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Drug Directory");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 350, 20));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 83, 1030, 10));

        tblDrugDirectory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Drug ID", "Drug Name", "ExpiryDate", "Manufacturer Name", "Number Of Units", "Price Of Unit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDrugDirectory);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 134, 970, 167));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("WareHouse Manager Workarea");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        btnPlaceOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPlaceOrder.setText("Place An Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });
        add(btnPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 310, -1, -1));

        btnViewAllOrders.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewAllOrders.setText("View All Orders");
        btnViewAllOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllOrdersActionPerformed(evt);
            }
        });
        add(btnViewAllOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 100, -1, -1));

        lblCountryState.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(lblCountryState, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 150, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed

        PlaceOrderToSalesManagerJPanel panel1 = new PlaceOrderToSalesManagerJPanel(userProcessContainer, warehouseEnterprise, userAccount, ecoSystem);
        userProcessContainer.add("Place order to Sales Manager", panel1);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void btnViewAllOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllOrdersActionPerformed

        ViewWarehouseAllOrdersJPanel panel2 = new ViewWarehouseAllOrdersJPanel(userProcessContainer, warehouseEnterprise, userAccount);
        userProcessContainer.add("View Warehouse All Orders", panel2);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewAllOrdersActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        Refresh();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnViewAllOrders;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCountryState;
    private javax.swing.JLabel lblName;
    private javax.swing.JTable tblDrugDirectory;
    // End of variables declaration//GEN-END:variables
}
