/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Manufacturer;

import Business.PreClinicalPackage.AnimalTreatment;

import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;

/**
 *
 * @author Rishabh
 */
public class AnimalTreatmentDetails extends javax.swing.JPanel {

    /**
     * Creates new form TreatmentDetails
     */
    private JPanel userProcessContainer;
    private AnimalTreatment animalTreatment;

    AnimalTreatmentDetails(JPanel userProcessContainer, AnimalTreatment animalTreatment) {
        initComponents();
        this.animalTreatment=animalTreatment;
        this.userProcessContainer=userProcessContainer;
        
       txtAnimal.setText(animalTreatment.getAnimal().getAnimalType());
       txtDrug.setText(animalTreatment.getDrug().getDrugName());
       txtResponse.setText(String.valueOf(animalTreatment.getResponse()));
       txtSideEffects.setText(String.valueOf(animalTreatment.getSideEffect()));
       
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        txtAnimal = new javax.swing.JTextField();
        txtResponse = new javax.swing.JTextField();
        txtDrug = new javax.swing.JTextField();
        lblAnimal = new javax.swing.JLabel();
        txtSideEffects = new javax.swing.JTextField();
        lblDrug = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        txtAnimal.setEnabled(false);
        add(txtAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 151, -1));

        txtResponse.setEnabled(false);
        add(txtResponse, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 151, -1));

        txtDrug.setEnabled(false);
        txtDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrugActionPerformed(evt);
            }
        });
        add(txtDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 151, -1));

        lblAnimal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAnimal.setText("Animal");
        add(lblAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 118, -1, -1));

        txtSideEffects.setEnabled(false);
        add(txtSideEffects, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 151, -1));

        lblDrug.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDrug.setText("Drug:");
        add(lblDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Response:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Side Effects:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Treatment Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 180, 27));

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 110, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrugActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrugActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblAnimal;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDrug;
    private javax.swing.JTextField txtAnimal;
    private javax.swing.JTextField txtDrug;
    private javax.swing.JTextField txtResponse;
    private javax.swing.JTextField txtSideEffects;
    // End of variables declaration//GEN-END:variables
}
