/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Manufacturer;

import Business.DrugPackage.Drug;
import Business.EcoSystem;
import Business.EnterprisePackage.Enterprise;
import Business.EnterprisePackage.ManufacturerEnterprise;
import Business.OrderPackage.Order;
import Business.UserAccountPackage.UserAccount;
import Business.WorkRequestPackage.ToDrugManagerWorkRequest;
import Business.WorkRequestPackage.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Atul
 */
public class DrugManagerJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount userAccount;
    ManufacturerEnterprise manufacturerEnterprise;
    EcoSystem ecoSystem;
    /**
     * Creates new form DrugManagerJPanel
     */
    

    public DrugManagerJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount account, EcoSystem business) {
        initComponents();
        this.ecoSystem = business;
        this.userProcessContainer = userProcessContainer;
        userAccount = account;
        manufacturerEnterprise = (ManufacturerEnterprise) enterprise;
        lblName.setText("Welcome : " + account.getEmployee().getFirstName());
        
        ((DefaultTableModel) DrugDirectoryJTable.getModel()).setRowCount(0);
        ((DefaultTableModel) requestsReceivedJTable.getModel()).setRowCount(0);
        

        Calendar currentDate = Calendar.getInstance();
        SimpleDateFormat formatter = new SimpleDateFormat("MMM/dd/yyyy");
        String dateNow = formatter.format(currentDate.getTime());
        lblDate.setText(dateNow);

        ((DefaultTableModel) tblDrugsPendingApproval.getModel()).setRowCount(0);

        for (Drug drug : manufacturerEnterprise.getUnApprovedDrugDirectory().getDrugDirectory()) {
            Object row[] = new Object[4];
 //           row[0] = drug.getDrugID();
            row[0] = drug;
            row[1] = drug.isIsApprovedByPreClinical();
            row[2] = drug.isIsApprovedByHospital();
 //           row[4] = drug.getNumberOfUnit();
            row[3] = drug.isIsWorkdonebyFDA();

            ((DefaultTableModel) tblDrugsPendingApproval.getModel()).addRow(row);
        }
        
        Refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        DrugDirectoryJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnAddDrug = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestsReceivedJTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnViewDetailsARP = new javax.swing.JButton();
        btnAssignToMe = new javax.swing.JButton();
        lblDate = new javax.swing.JLabel();
        lblCountryState = new javax.swing.JLabel();
        btnViewDetailsARP1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblDrugsPendingApproval = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnCreateDrug = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Sales Requests");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        lblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 20));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 980, 10));

        DrugDirectoryJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Drug ID", "Drug Name", "ExpiryDate", "Number Of Units", "Price Of Unit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(DrugDirectoryJTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 960, 140));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Drug Manager Workarea");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        btnAddDrug.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddDrug.setText("Add Drug");
        btnAddDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDrugActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, -1, -1));

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel2.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 70, -1, -1));

        requestsReceivedJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "OrderID", "Sender", "Receiver", "Status", "Manufacturer Name", "SendingDate", "Receing Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(requestsReceivedJTable);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 960, 120));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Request Received From Sales Manager");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        btnViewDetailsARP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewDetailsARP.setText("View Details");
        btnViewDetailsARP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsARPActionPerformed(evt);
            }
        });
        jPanel2.add(btnViewDetailsARP, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 470, -1, -1));

        btnAssignToMe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAssignToMe.setText("Assign To Me");
        btnAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToMeActionPerformed(evt);
            }
        });
        jPanel2.add(btnAssignToMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, -1, 30));

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 110, 20));

        lblCountryState.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(lblCountryState, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 150, 20));

        btnViewDetailsARP1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewDetailsARP1.setText("View Details");
        btnViewDetailsARP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsARP1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnViewDetailsARP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 670, -1, 30));

        tblDrugsPendingApproval.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Drug Name", "PreClinical Status", "Hospital Status", "FDA Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblDrugsPendingApproval);
        if (tblDrugsPendingApproval.getColumnModel().getColumnCount() > 0) {
            tblDrugsPendingApproval.getColumnModel().getColumn(0).setResizable(false);
            tblDrugsPendingApproval.getColumnModel().getColumn(1).setResizable(false);
            tblDrugsPendingApproval.getColumnModel().getColumn(2).setResizable(false);
            tblDrugsPendingApproval.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 960, 120));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Drugs Pending for Approval");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, -1));

        btnCreateDrug.setText("Create New Drug");
        btnCreateDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDrugActionPerformed(evt);
            }
        });
        jPanel2.add(btnCreateDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 670, 130, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Drug Directory");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 976, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDrugActionPerformed

        CreateDrugJPanel panel = new CreateDrugJPanel(userProcessContainer, manufacturerEnterprise, userAccount);
        userProcessContainer.add("Create Drug", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddDrugActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        Refresh();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnViewDetailsARPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsARPActionPerformed

        int selectedRow = requestsReceivedJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select Row to view details");
            return;
        }

        WorkRequest workRequest = (WorkRequest) requestsReceivedJTable.getValueAt(selectedRow, 0);
        Order order = ((ToDrugManagerWorkRequest) workRequest).getOrder();
        OrderDetailsJPanel panel = new OrderDetailsJPanel(userProcessContainer, order);
        userProcessContainer.add("by drug manager order received details", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewDetailsARPActionPerformed

    private void btnAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToMeActionPerformed

        int selectedRow = requestsReceivedJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "select row");
            return;
        }

        WorkRequest wr1 = (WorkRequest) requestsReceivedJTable.getValueAt(selectedRow, 0);

        if (((ToDrugManagerWorkRequest) wr1).getStatus().equals(WorkRequest.Done)) {
            JOptionPane.showMessageDialog(null, "Already Assigned");
            return;
        }

        wr1.setStatus(WorkRequest.Done);
        wr1.setReceiver(userAccount);
        wr1.setReceivingDate(lblDate.getText());

        Refresh();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAssignToMeActionPerformed

    private void btnViewDetailsARP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsARP1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDrugsPendingApproval.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select Row to view details");
            return;
        }
        else
        {
            Drug  d = (Drug) tblDrugsPendingApproval.getValueAt(selectedRow, 0);

            
            int stage = 3;
            Boolean flagfda = (Boolean) tblDrugsPendingApproval.getValueAt(selectedRow, 3);
            if(flagfda==false)
            {
            Boolean flagHospital = (Boolean) tblDrugsPendingApproval.getValueAt(selectedRow, 2);
                if( flagHospital==false)
                {
                    Boolean flagPreclinical = (Boolean) tblDrugsPendingApproval.getValueAt(selectedRow, 1);
                    stage = 1;
                    if(flagPreclinical == false)
                    {
                        stage = 0;
                    }
                }
            }
            DrugApprovalStatusJPanel panel = new DrugApprovalStatusJPanel(userProcessContainer,manufacturerEnterprise,userAccount,d,stage, ecoSystem);
            userProcessContainer.add("Create Un approved Drug", panel);
            CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
            cardLayout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnViewDetailsARP1ActionPerformed

    private void btnCreateDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDrugActionPerformed
        // TODO add your handling code here:
        
        CreateUnApprovedDrug panel = new CreateUnApprovedDrug(userProcessContainer, manufacturerEnterprise, userAccount);
        userProcessContainer.add("Create Un approved Drug", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnCreateDrugActionPerformed

    public void Refresh() {
        
        ((DefaultTableModel) DrugDirectoryJTable.getModel()).setRowCount(0);
        ((DefaultTableModel) requestsReceivedJTable.getModel()).setRowCount(0);

        for (Drug drug : manufacturerEnterprise.getDrugDirectory().getDrugDirectory()) {
            Object row[] = new Object[5];
            row[0] = drug.getDrugId();
            row[1] = drug.getDrugName();
            row[2] = drug.getExpiryDate();
           // row[2] = drug.getManufacturerName();
            row[3] = drug.getNoOfUnits();
            row[4] = drug.getUnitPrice();

            ((DefaultTableModel) DrugDirectoryJTable.getModel()).addRow(row);
        }

        for (WorkRequest wr : manufacturerEnterprise.getDrugManagerOrganization().getWorkQueue().getWorkRequestQueue()) {

            if(wr instanceof ToDrugManagerWorkRequest)
            {
            Object row[] = new Object[7];
            row[0] = (ToDrugManagerWorkRequest) wr;
            row[1] = wr.getSender();
            row[2] = wr.getReceiver();
            row[3] = wr.getStatus();
            row[4] = (((ToDrugManagerWorkRequest) wr).getManufacturerEnterprise());
            row[5] = wr.getSendingDate();
            row[6] = wr.getReceivingDate();

            ((DefaultTableModel) requestsReceivedJTable.getModel()).addRow(row);
            }
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DrugDirectoryJTable;
    private javax.swing.JButton btnAddDrug;
    private javax.swing.JButton btnAssignToMe;
    private javax.swing.JButton btnCreateDrug;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnViewDetailsARP;
    private javax.swing.JButton btnViewDetailsARP1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCountryState;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblName;
    private javax.swing.JTable requestsReceivedJTable;
    private javax.swing.JTable tblDrugsPendingApproval;
    // End of variables declaration//GEN-END:variables
}
