/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Manufacturer;

import Business.DrugPackage.Drug;
import Business.EnterprisePackage.ManufacturerEnterprise;
import Business.OrderPackage.Order;
import Business.OrderPackage.OrderItem;
import Business.UserAccountPackage.UserAccount;
import Business.WorkRequestPackage.ToDrugManagerWorkRequest;
import Business.WorkRequestPackage.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Atul
 */
public class PlaceRequestToDrugManagerJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount userAccount;
    ManufacturerEnterprise manufacturerEnterprise;
    Order order;
    /**
     * Creates new form PlaceRequestToDrugManagerJPanel
     */
    public PlaceRequestToDrugManagerJPanel(JPanel j, ManufacturerEnterprise m, UserAccount u) {
        initComponents();
        userProcessContainer = j;
        manufacturerEnterprise = m;
        userAccount = u;

        Calendar currentDate = Calendar.getInstance();
        SimpleDateFormat formatter = new SimpleDateFormat("MMM/dd/yyyy");
        String dateNow = formatter.format(currentDate.getTime());
        lblDate.setText(dateNow);

        order = new Order();
        lblOrderID.setText("Order ID : " + order.getOrderID());

        txtSelectedManufacturer.setText(manufacturerEnterprise.getOrganizationName());

        int rowCount = myCartJTable.getRowCount();

        for (int i = rowCount - 1; i >= 0; i--) {
            ((DefaultTableModel) myCartJTable.getModel()).removeRow(i);
        }

        cmbDrugs.removeAll();
        
        
        
        for(Drug d :manufacturerEnterprise.getDrugDirectory().getDrugDirectory())
        {
            String drugName= d.getDrugName();
            cmbDrugs.addItem(drugName);
        }

    }

    
    public void Refresh() {
        int rowCount = myCartJTable.getRowCount();

        for (int i = rowCount - 1; i >= 0; i--) {
            ((DefaultTableModel) myCartJTable.getModel()).removeRow(i);
        }

        for (OrderItem orderItem : order.getOrderItemList()) {
            Object row[] = new Object[2];
            row[0] = orderItem;
            row[1] = orderItem.getQuantity();

            ((DefaultTableModel) myCartJTable.getModel()).addRow(row);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnSubmitOrder = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        myCartJTable = new javax.swing.JTable();
        lblOrderID = new javax.swing.JLabel();
        btnAddtoCart = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        txtSelectedManufacturer = new javax.swing.JTextField();
        cmbDrugs = new javax.swing.JComboBox<>();
        backJButton = new javax.swing.JButton();

        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("My Cart");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Drug Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));
        jPanel1.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 140, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Selected Manufacturer");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        btnSubmitOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSubmitOrder.setText("Submit Order");
        btnSubmitOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitOrderActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmitOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 485, -1, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 67, 1030, 10));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Quantity");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        myCartJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Drug Name", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(myCartJTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 230, 340));

        lblOrderID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(lblOrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 160, 30));

        btnAddtoCart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddtoCart.setText("Add To Cart");
        btnAddtoCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtoCartActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddtoCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, -1, -1));

        btnRemove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Place Order To Drug Manager");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 110, 20));

        txtSelectedManufacturer.setEnabled(false);
        jPanel1.add(txtSelectedManufacturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 140, -1));

        jPanel1.add(cmbDrugs, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 140, -1));

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitOrderActionPerformed

        if (order.getOrderItemList().size() == 0) {
            JOptionPane.showMessageDialog(null, "Nothing In Cart");
            return;
        }

        ToDrugManagerWorkRequest wr = new ToDrugManagerWorkRequest();
        wr.setOrder(order);
        wr.setSender(userAccount);
        wr.setStatus(WorkRequest.UnderPro);
        wr.setManufacturerEnterprise(manufacturerEnterprise);
        wr.setSendingDate(lblDate.getText());

        manufacturerEnterprise.getDrugManagerOrganization().getWorkQueue().getWorkRequestQueue().add(wr);

        JOptionPane.showMessageDialog(null, "Order " + order.getOrderID() + " Placed Successfully");

        SalesManagerJPanel panel = new SalesManagerJPanel(userProcessContainer, manufacturerEnterprise, userAccount);
        userProcessContainer.add("back to ssales manager", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitOrderActionPerformed

    private void btnAddtoCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtoCartActionPerformed

        int quantity = 0;
        try {
            quantity = Integer.parseInt(txtQuantity.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Quantity must be an interger");
            return;
        }

        OrderItem orderItem = order.newOrderItem();

        orderItem.setDrugName(cmbDrugs.getSelectedItem() + "");
        orderItem.setQuantity(quantity);

        Refresh();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddtoCartActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed

        int selectedRow = myCartJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select Row to Remove Drug from MyCart");
            return;
        }

        OrderItem orderItem = (OrderItem) myCartJTable.getValueAt(selectedRow, 0);
        order.removeOrderItem(orderItem);

        Refresh();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnAddtoCart;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSubmitOrder;
    private javax.swing.JComboBox<String> cmbDrugs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblOrderID;
    private javax.swing.JTable myCartJTable;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSelectedManufacturer;
    // End of variables declaration//GEN-END:variables
}
