/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Manufacturer;

import Business.DrugPackage.Drug;
import Business.EnterprisePackage.Enterprise;
import Business.EnterprisePackage.ManufacturerEnterprise;
import Business.OrderPackage.Order;
import Business.UserAccountPackage.UserAccount;
import Business.WorkRequestPackage.ToDrugManagerWorkRequest;
import Business.WorkRequestPackage.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Atul
 */
public class SalesManagerJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount userAccount;
    ManufacturerEnterprise manufacturerEnterprise;
    /**
     * Creates new form SalesManagerJPanel
     */
    public SalesManagerJPanel(JPanel j, Enterprise e, UserAccount u) {
        initComponents();
        userProcessContainer = j;
        manufacturerEnterprise = (ManufacturerEnterprise) e;
        userAccount = u;

        lblName.setText("Sales Manager Name is : " + u.getEmployee().getFirstName());
        int rowConut = DrugDirectoryJTable.getRowCount();
        for (int i = rowConut - 1; i >= 0; i--) {
            ((DefaultTableModel) DrugDirectoryJTable.getModel()).removeRow(i);
        }
        int rowCount1 = requestsPlacedJTable.getRowCount();

        for (int i = rowCount1 - 1; i >= 0; i--) {
            ((DefaultTableModel) requestsPlacedJTable.getModel()).removeRow(i);
        }
        Refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        DrugDirectoryJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnViewAllOrders = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnPlaceRequestToCreateDrug = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestsPlacedJTable = new javax.swing.JTable();
        btnViewDetailsARP = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblCountryState = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Request Placed To Drug Manager");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        lblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 290, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 83, 990, 10));

        DrugDirectoryJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Drug ID", "Drug Name", "ExpiryDate", "Manufacturer Name", "Number Of Units", "Price Of Unit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(DrugDirectoryJTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 970, 120));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Sales Manager Workarea");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        btnViewAllOrders.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewAllOrders.setText("View All Orders");
        btnViewAllOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllOrdersActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewAllOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, -1, -1));

        btnPlaceRequestToCreateDrug.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPlaceRequestToCreateDrug.setText("Place Reqeust To Create Drug");
        btnPlaceRequestToCreateDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceRequestToCreateDrugActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlaceRequestToCreateDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, -1, -1));

        requestsPlacedJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "OrderID", "Sender", "Receiver", "Status", "Manufacturer Name", "SendingDate", "Receiving Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(requestsPlacedJTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 970, 110));

        btnViewDetailsARP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewDetailsARP.setText("View Details");
        btnViewDetailsARP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsARPActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewDetailsARP, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 480, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Drug Directory");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        lblCountryState.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(lblCountryState, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 150, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void Refresh() {
        int rowConut = DrugDirectoryJTable.getRowCount();
        for (int i = rowConut - 1; i >= 0; i--) {
            ((DefaultTableModel) DrugDirectoryJTable.getModel()).removeRow(i);
        }

        int rowCount1 = requestsPlacedJTable.getRowCount();

        for (int i = rowCount1 - 1; i >= 0; i--) {
            ((DefaultTableModel) requestsPlacedJTable.getModel()).removeRow(i);
        }

        for (Drug drug : manufacturerEnterprise.getDrugDirectory().getDrugDirectory()) {
            Object row[] = new Object[6];
            row[1] = drug.getDrugName();
            row[2] = drug.getExpiryDate();
            row[3] = drug.getManufacturerName();
            row[4] = drug.getNoOfUnits();
            row[5] = drug.getUnitPrice();

            if (!(drug.getNoOfUnits() == 0)) {
                ((DefaultTableModel) DrugDirectoryJTable.getModel()).addRow(row);
            }
        }

        for (WorkRequest wr : manufacturerEnterprise.getDrugManagerOrganization().getWorkQueue().getWorkRequestQueue()) 
        {

            if(wr instanceof ToDrugManagerWorkRequest)
            {
            Object row[] = new Object[7];
            row[0] = (ToDrugManagerWorkRequest) wr;
            row[1] = wr.getSender();
            row[2] = wr.getReceiver();
            row[3] = wr.getStatus();
            row[4] = (((ToDrugManagerWorkRequest) wr).getManufacturerEnterprise());
            row[5] = wr.getSendingDate();
            row[6] = wr.getReceivingDate();

            ((DefaultTableModel) requestsPlacedJTable.getModel()).addRow(row);
            }
        }
    }
    
    private void btnViewAllOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllOrdersActionPerformed

        ViewSalesAllOrdersJPanel panel = new ViewSalesAllOrdersJPanel(userProcessContainer, manufacturerEnterprise, userAccount);
        userProcessContainer.add("view manufacturer all orders", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewAllOrdersActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        Refresh();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnPlaceRequestToCreateDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceRequestToCreateDrugActionPerformed

        PlaceRequestToDrugManagerJPanel panel = new PlaceRequestToDrugManagerJPanel(userProcessContainer, manufacturerEnterprise, userAccount);
        userProcessContainer.add("place order to drug manager", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlaceRequestToCreateDrugActionPerformed

    private void btnViewDetailsARPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsARPActionPerformed

        int selectedRow = requestsPlacedJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select Row to view details");
            return;
        }

        WorkRequest workRequest = (WorkRequest) requestsPlacedJTable.getValueAt(selectedRow, 0);
        Order order = ((ToDrugManagerWorkRequest) workRequest).getOrder();
        OrderDetailsJPanel panel = new OrderDetailsJPanel(userProcessContainer, order);
        userProcessContainer.add("to drug manager order placed details", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewDetailsARPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DrugDirectoryJTable;
    private javax.swing.JButton btnPlaceRequestToCreateDrug;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnViewAllOrders;
    private javax.swing.JButton btnViewDetailsARP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCountryState;
    private javax.swing.JLabel lblName;
    private javax.swing.JTable requestsPlacedJTable;
    // End of variables declaration//GEN-END:variables
}
