/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Manufacturer;

import Business.DrugPackage.Drug;
import Business.DrugPackage.DrugDirectory;
import Business.EnterprisePackage.ManufacturerEnterprise;
import Business.PreClinicalPackage.Animal;
import Business.PreClinicalPackage.AnimalDirectory;
import Business.PreClinicalPackage.AnimalTreatment;
import Business.PreClinicalPackage.AnimalTreatmentHistory;
import Business.UserAccountPackage.UserAccount;
import Business.WorkRequestPackage.ForClinicalFromManuToHosp;
import Business.WorkRequestPackage.ForTestingByManuToPreclinical;
import Business.WorkRequestPackage.WorkRequest;

import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Rishabh
 */
public class TreatAnimalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TreatPatientJPanel
     */
    private JPanel userProcessContainer;
    private AnimalDirectory  animalDirectory;
    private DrugDirectory drugDirectory;
    private AnimalTreatmentHistory animalTreatmentHistory;
    private ManufacturerEnterprise manufacturerEnterprise;
    private UserAccount userAccount;
    private DrugDirectory DrugDirectoryforTest;

    TreatAnimalJPanel(JPanel userProcessContainer, ManufacturerEnterprise manufacturerEnterprise , UserAccount ua) {
       initComponents();
       this.userProcessContainer=userProcessContainer;
       this.manufacturerEnterprise= manufacturerEnterprise;
       this.userAccount=userAccount;
       animalTreatmentHistory=manufacturerEnterprise.getPreClinicalTesterOrgnization().getAnimalTreatmentHistory();
       
        Calendar currentDate = Calendar.getInstance();
        SimpleDateFormat formatter = new SimpleDateFormat("MMM/dd/yyyy");
        String dateNow = formatter.format(currentDate.getTime());
        lblDate.setText(dateNow);
        cmbxDrug.removeAllItems();
        
        
        refresh();
    }
    public void refresh(){
       cmbxAnimals.removeAllItems();
       for(Animal animal:manufacturerEnterprise.getPreClinicalTesterOrgnization().getAnimalDirectory().getAnimalDirectory()){
           cmbxAnimals.addItem(animal);
       }
       
       for(WorkRequest wr1:manufacturerEnterprise.getPreClinicalTesterOrgnization().getWorkQueue().getWorkRequestQueue())
       {
           if(wr1 instanceof ForTestingByManuToPreclinical)
           {
           ForTestingByManuToPreclinical wr = (ForTestingByManuToPreclinical)wr1;
           if(!(wr.getStatus().equals("Done")))
           {
               cmbxDrug.addItem(wr.getDrug());
           }
           }
       }
      
       
       
           
       
       
       txtResponse.setText("");
       txtSideEffect.setText("");
       txtAge.setText("");
       txtDosage.setText("");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtResponse = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtSideEffect = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnTreat = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtDosage = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        cmbxAnimals = new javax.swing.JComboBox();
        lblDate = new javax.swing.JLabel();
        cmbxDrug = new javax.swing.JComboBox();

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Name:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Animal Test Area");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Drug:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Response:");

        txtResponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResponseActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Dosage");

        txtSideEffect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSideEffectActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Side Effect:");

        btnTreat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTreat.setText("Treat");
        btnTreat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreatActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Age");

        lblDate.setText("jLabel3");

        cmbxDrug.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 516, Short.MAX_VALUE)
                .addComponent(lblDate)
                .addGap(317, 317, 317))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel13)
                                    .addComponent(btnBack))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAge, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(cmbxAnimals, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtResponse, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(txtSideEffect, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDosage)
                            .addComponent(cmbxDrug, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(btnTreat, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDate)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(cmbxAnimals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbxDrug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDosage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtResponse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSideEffect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(btnTreat)
                .addGap(109, 109, 109)
                .addComponent(btnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtResponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResponseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResponseActionPerformed

    private void txtSideEffectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSideEffectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSideEffectActionPerformed

    private void btnTreatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreatActionPerformed
        
        
        
        AnimalTreatment treatment=animalTreatmentHistory.addAnimalTreatment();
        treatment.setAnimal((Animal)cmbxAnimals.getSelectedItem());
        Drug selectedDrug=(Drug)cmbxDrug.getSelectedItem();
        treatment.setDrug(selectedDrug);
        treatment.setDosage(txtDosage.getText());
        treatment.setResponse(Integer.parseInt(txtResponse.getText()));
        treatment.setSideEffect(Integer.parseInt(txtSideEffect.getText()));
        
        for(WorkRequest wr:manufacturerEnterprise.getPreClinicalTesterOrgnization().getWorkQueue().getWorkRequestQueue())
        {
            ForTestingByManuToPreclinical forTestingByManuToPreclinical = (ForTestingByManuToPreclinical)wr;
            if(forTestingByManuToPreclinical.getDrug().equals(selectedDrug))
                    {
                        forTestingByManuToPreclinical.setStatus(WorkRequest.Done);
                        forTestingByManuToPreclinical.setReceiver(userAccount);
                        forTestingByManuToPreclinical.setReceivingDate(lblDate.getText());
                        selectedDrug.setIsApprovedByPreClinical(true);
                        
                    }
        }
        
        refresh();
        
         JOptionPane.showMessageDialog(null, "Animal treatment is added successfully!!");

// TODO add your handling code here:
    }//GEN-LAST:event_btnTreatActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] component=userProcessContainer.getComponents();
        Component previous=component[component.length-1];
        PreClinicalJPanel PreClinicalJPanel=(PreClinicalJPanel)previous;
        PreClinicalJPanel.refresh();
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnTreat;
    private javax.swing.JComboBox cmbxAnimals;
    private javax.swing.JComboBox cmbxDrug;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblDate;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtDosage;
    private javax.swing.JTextField txtResponse;
    private javax.swing.JTextField txtSideEffect;
    // End of variables declaration//GEN-END:variables
}
