/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Manufacturer;

import Business.EnterprisePackage.ManufacturerEnterprise;
import Business.EnterprisePackage.WarehouseEnterprise;
import Business.OrderPackage.Batch;
import Business.OrderPackage.Order;
import Business.UserAccountPackage.UserAccount;
import Business.WorkRequestPackage.FromSalesWorkRequest;
import Business.WorkRequestPackage.FromWareHouseWorkRequest;
import Business.WorkRequestPackage.ToSalesWorkRequest;
import Business.WorkRequestPackage.WorkRequest;
import UserInterface.Hospital.OrderBatchDetailsJPanel;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Atul
 */
public class ViewSalesAllOrdersJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount userAccount;
    ManufacturerEnterprise manufacturerEnterprise;
    /**
     * Creates new form ViewSalesAllOrdersJPanel
     */
    public ViewSalesAllOrdersJPanel(JPanel j, ManufacturerEnterprise wh, UserAccount u) {
        initComponents();
        userProcessContainer = j;
        manufacturerEnterprise = wh;
        userAccount = u;

        Calendar currentDate = Calendar.getInstance();
        SimpleDateFormat formatter = new SimpleDateFormat("MMM/dd/yyyy");
        String dateNow = formatter.format(currentDate.getTime());
        lblDate.setText(dateNow);

        Refresh();
    }

    public void Refresh() {

        int rowCount = ordersReceivedJTable.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            ((DefaultTableModel) ordersReceivedJTable.getModel()).removeRow(i);
        }

        int rowCount1 = ordersPlacedJTable.getRowCount();

        for (int i = rowCount1 - 1; i >= 0; i--) {
            ((DefaultTableModel) ordersPlacedJTable.getModel()).removeRow(i);
        }

        for (WorkRequest wr : manufacturerEnterprise.getSalesManagerOrganization().getWorkQueue().getWorkRequestQueue()) {

            if(wr instanceof FromSalesWorkRequest)
            {
            Object row[] = new Object[8];
            row[0] = (FromSalesWorkRequest) wr;
            row[1] = ((FromSalesWorkRequest) wr).getBatch();
            row[2] = wr.getSender();
            row[3] = wr.getReceiver();
            row[4] = wr.getStatus();
            row[5] = (((FromSalesWorkRequest) wr).getWareHouseEnterprise());
            row[6] = wr.getSendingDate();
            row[7] = wr.getReceivingDate();

            ((DefaultTableModel) ordersPlacedJTable.getModel()).addRow(row);
            }
        }

        for (WorkRequest wr : (manufacturerEnterprise.getSalesManagerOrganization().getWorkQueue().getWorkRequestQueue())) {
            if(wr instanceof ToSalesWorkRequest )
            {
            Object row[] = new Object[7];
            row[0] = (ToSalesWorkRequest) wr;
            row[1] = wr.getSender();
            row[2] = wr.getReceiver();
            row[3] = wr.getStatus();
            row[4] = ((ToSalesWorkRequest) wr).getWareHouseEnterprise();
            row[5] = wr.getSendingDate();
            row[6] = wr.getReceivingDate();

            ((DefaultTableModel) ordersReceivedJTable.getModel()).addRow(row);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAssignToMe = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordersReceivedJTable = new javax.swing.JTable();
        lblDate = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnViewDetailsOR = new javax.swing.JButton();
        btnProcess = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ordersPlacedJTable = new javax.swing.JTable();
        btnViewDetailsAPO = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Order Received From WareHouse");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 320, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1000, 10));

        btnAssignToMe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAssignToMe.setText("Assign To Me");
        btnAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToMeActionPerformed(evt);
            }
        });
        jPanel1.add(btnAssignToMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, -1, 30));

        ordersReceivedJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "OrderID", "Sender", "Receiver", "Status", "WareHouse Name", "Sending Date", "Receiving Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ordersReceivedJTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 960, 170));

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 110, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Sales Manager workarea");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 320, -1));

        btnViewDetailsOR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewDetailsOR.setText("View Details");
        btnViewDetailsOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsORActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewDetailsOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 500, -1, -1));

        btnProcess.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        jPanel1.add(btnProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, -1, 30));

        ordersPlacedJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "OrderID", "Batch ID", "Sender", "Receiver", "Status", "WareHouse Name", "SendingDate", "Receing Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ordersPlacedJTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 970, 110));

        btnViewDetailsAPO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewDetailsAPO.setText("View Details");
        btnViewDetailsAPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsAPOActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewDetailsAPO, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, -1, -1));

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("All Orders Placed To WareHouse");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 330, -1));

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 997, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 997, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToMeActionPerformed

        int selectedRow = ordersReceivedJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "select row");
            return;
        }

        WorkRequest wr1 = (WorkRequest) ordersReceivedJTable.getValueAt(selectedRow, 0);

        if (((ToSalesWorkRequest) wr1).getStatus().equals(WorkRequest.Recieve) || ((ToSalesWorkRequest) wr1).getStatus().equals(WorkRequest.Done)) {
            JOptionPane.showMessageDialog(null, "Already Assigned");
            return;
        }

        wr1.setStatus(WorkRequest.Recieve);
        wr1.setReceiver(userAccount);
        wr1.setReceivingDate(lblDate.getText());

        WarehouseEnterprise whereHouseEnterprise = ((ToSalesWorkRequest) wr1).getWareHouseEnterprise();
        for (WorkRequest wr : whereHouseEnterprise.getWarehouseManagerOrganization().getWorkQueue().getWorkRequestQueue()) {
            if(wr instanceof FromWareHouseWorkRequest) {
            if ((((FromWareHouseWorkRequest) wr).getOrder().getOrderID()).equals(((ToSalesWorkRequest) wr1).getOrder().getOrderID())) {
                wr.setReceiver(userAccount);
                wr.setStatus(WorkRequest.Sent);
                wr.setReceivingDate(lblDate.getText());
            }
            }
        }

        Refresh();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAssignToMeActionPerformed

    private void btnViewDetailsORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsORActionPerformed

        int selectedRow = ordersReceivedJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select Row to view details");
            return;
        }

        WorkRequest workRequest = (WorkRequest) ordersReceivedJTable.getValueAt(selectedRow, 0);
        Order order = ((ToSalesWorkRequest) workRequest).getOrder();
        OrderDetailsJPanel panel = new OrderDetailsJPanel(userProcessContainer, order);
        userProcessContainer.add("sales Orders Received details", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewDetailsORActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed

        int selectedRow = ordersReceivedJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select Row to Process");
            return;
        }

        WorkRequest workRequest = (WorkRequest) ordersReceivedJTable.getValueAt(selectedRow, 0);
        for (WorkRequest wr : manufacturerEnterprise.getSalesManagerOrganization().getWorkQueue().getWorkRequestQueue()) {
            if(wr instanceof FromSalesWorkRequest){
            if (((FromSalesWorkRequest) wr).getOrder().getOrderID().equals(((ToSalesWorkRequest) workRequest).getOrder().getOrderID())) {
                JOptionPane.showMessageDialog(null, "Order Already Processed ");
                return;
            }}
        }

        if (!(workRequest.getStatus().equals(WorkRequest.Recieve))) {
            JOptionPane.showMessageDialog(null, "Assign To Yourself Before Processing");
            return;
        }

        if ((workRequest.getStatus().equals(WorkRequest.Done))) {
            JOptionPane.showMessageDialog(null, "Work is Already Done");
            return;
        }

        ReplyOrderToInventoryJPanel panel = new ReplyOrderToInventoryJPanel(userProcessContainer, manufacturerEnterprise, userAccount, workRequest);
        userProcessContainer.add("place order to inventory", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnViewDetailsAPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsAPOActionPerformed

        int selectedRow = ordersPlacedJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select Row to view details");
            return;
        }

        WorkRequest workRequest = (WorkRequest) ordersPlacedJTable.getValueAt(selectedRow, 0);
        Order order = ((FromSalesWorkRequest) workRequest).getOrder();
        Batch batch = ((FromSalesWorkRequest) workRequest).getBatch();
        OrderBatchDetailsJPanel panel = new OrderBatchDetailsJPanel(userProcessContainer, order, batch);
        userProcessContainer.add("warehouse Orders placed details", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewDetailsAPOActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed

        Refresh();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnAssignToMe;
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnViewDetailsAPO;
    private javax.swing.JButton btnViewDetailsOR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JTable ordersPlacedJTable;
    private javax.swing.JTable ordersReceivedJTable;
    // End of variables declaration//GEN-END:variables
}
