/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.StateLicense;

import Business.EnterprisePackage.Enterprise;
import Business.EnterprisePackage.LicenseEnterprise;
import Business.UserAccountPackage.UserAccount;
import Business.WorkRequestPackage.ForLicenceByHosWorkRequest;
import Business.WorkRequestPackage.ForLicenceByWareHWorkRequest;
import Business.WorkRequestPackage.WorkRequest;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rishabh
 */
public class StateLevelLicenseAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StateLevelLicenseAdminJPanel
     */
    JPanel userProcessContainer;
    LicenseEnterprise enterprise;
    UserAccount account;

    public StateLevelLicenseAdminJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount account) {
        initComponents();
        this.account=account;
        this.enterprise= (LicenseEnterprise) enterprise;
        this.userProcessContainer=userProcessContainer;
        Calendar currentDate = Calendar.getInstance();
        SimpleDateFormat formatter = new SimpleDateFormat("MMM/dd/yyyy");
        String dateNow = formatter.format(currentDate.getTime());
        lblDate.setText(dateNow);
        lblName.setText("State Level Licensing Admin Name is : " + account.getEmployee().getFirstName());
        

       

        

        Refresh();
    }
public void Refresh() {
        int rowCount = tblRequestForLicenceByHospital.getRowCount();
        DefaultTableModel dtm=(DefaultTableModel)tblRequestForLicenceByHospital.getModel();
        for(int i=rowCount-1;i>=0;i--){
            
            dtm.removeRow(i);
        }
        for (WorkRequest work : enterprise.getWorkQueue().getWorkRequestQueue()) {

            if(work instanceof ForLicenceByHosWorkRequest)
            {
            Object row[] = new Object[6];
            row[0] = (ForLicenceByHosWorkRequest) work;
            row[1] = work.getSender();
            row[2] = work.getReceiver();
            row[3] = work.getStatus();
            row[4] = work.getSendingDate();
            row[5] = work.getReceivingDate();

            dtm.addRow(row);
            }
        }

        int rowCount1 = tblRequestForLicenceByWarehouse.getRowCount();
        DefaultTableModel dtm1=(DefaultTableModel)tblRequestForLicenceByWarehouse.getModel();
        for (int i = rowCount1 - 1; i >= 0; i--) {
            dtm1.removeRow(i);
        }

        for (WorkRequest work1 : enterprise.getWorkQueue().getWorkRequestQueue()) {

            if(work1 instanceof ForLicenceByWareHWorkRequest )
            {
            Object row[] = new Object[6];
            row[0] = (ForLicenceByWareHWorkRequest) work1;
            row[1] = work1.getSender();
            row[2] = work1.getReceiver();
            row[3] = work1.getStatus();
            row[4] = work1.getSendingDate();
            row[5] = work1.getReceivingDate();

            dtm1.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRequestForLicenceByHospital = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRequestForLicenceByWarehouse = new javax.swing.JTable();
        lblCountryState = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        btnApproveWarehouse = new javax.swing.JButton();
        btnApproveHospital = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("State Level Licensing Admin WorkArea");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        lblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 350, 20));

        tblRequestForLicenceByHospital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Hospital Name", "Sender", "Receiver", "Status", "SendingDate", "Receiving Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblRequestForLicenceByHospital);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 950, 140));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Request For Licence By Hospitals");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 430, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Request For Licence By WareHouses");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 430, -1));

        tblRequestForLicenceByWarehouse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "WareHouse Name", "Sender", "Receiver", "Status", "SendingDate", "Receiving Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblRequestForLicenceByWarehouse);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 950, 140));

        lblCountryState.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(lblCountryState, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 150, 20));

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 110, 20));

        btnApproveWarehouse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnApproveWarehouse.setText("Approve");
        btnApproveWarehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveWarehouseActionPerformed(evt);
            }
        });
        add(btnApproveWarehouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 270, -1, -1));

        btnApproveHospital.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnApproveHospital.setText("Approve");
        btnApproveHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveHospitalActionPerformed(evt);
            }
        });
        add(btnApproveHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 490, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveWarehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveWarehouseActionPerformed

        int selectedRow = tblRequestForLicenceByWarehouse.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select Row to Approve licence");
            return;
        }

        WorkRequest workRequest = (WorkRequest) tblRequestForLicenceByWarehouse.getValueAt(selectedRow, 0);

        if (workRequest.getStatus().equals(WorkRequest.Done)) {
            JOptionPane.showMessageDialog(null, "Licence Already Approved");
            return;
        }

        ((ForLicenceByWareHWorkRequest) workRequest).getWareHouseEnterprise().setLicence(Enterprise.LicApproved);
        workRequest.setStatus(WorkRequest.Done);
        workRequest.setReceiver(account);
        workRequest.setReceivingDate(lblDate.getText());
        Refresh();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnApproveWarehouseActionPerformed

    private void btnApproveHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveHospitalActionPerformed

        int selectedRow = tblRequestForLicenceByHospital.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select Row to Approve licence");
            return;
        }

        WorkRequest workRequest = (WorkRequest) tblRequestForLicenceByHospital.getValueAt(selectedRow, 0);

        if (workRequest.getStatus().equals(WorkRequest.Done)) {
            JOptionPane.showMessageDialog(null, "Licence Already Approved");
            return;
        }

        ((ForLicenceByHosWorkRequest) workRequest).getHospitalEnterprise().setLicence(Enterprise.LicApproved);
        workRequest.setStatus(WorkRequest.Done);
        workRequest.setReceiver(account);
        workRequest.setReceivingDate(lblDate.getText());
        Refresh();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnApproveHospitalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApproveHospital;
    private javax.swing.JButton btnApproveWarehouse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCountryState;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblName;
    private javax.swing.JTable tblRequestForLicenceByHospital;
    private javax.swing.JTable tblRequestForLicenceByWarehouse;
    // End of variables declaration//GEN-END:variables
}
