/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital;
import Business.DrugPackage.Drug;
import Business.EcoSystem;
import Business.EmployeePackage.Employee;
import Business.EnterprisePackage.*;
import Business.NetworkPackage.Network;
import Business.OrganizationPackage.Organization;
import Business.RolePackage.DispenserManagerRole;
import Business.RolePackage.DoctorRole;
import Business.RolePackage.PreClinicalTesterRole;
import Business.UserAccountPackage.UserAccount;
import Business.WorkRequestPackage.AddDrugToYourDirectory;
import Business.WorkRequestPackage.ForLicenceByHosWorkRequest;
import Business.WorkRequestPackage.WorkRequest;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Rishabh
 */
public class HospitalAdminJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    HospitalEnterprise hospitalEnterprise;
    UserAccount account;
    /**
     * Creates new form HospitalAdminJPanel
     */
    public HospitalAdminJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount account) {
        initComponents();
        this.account=account;
        this.hospitalEnterprise=(HospitalEnterprise) enterprise;
        this.userProcessContainer=userProcessContainer;
        
        lblAdmin.setText("Welcome : " + account.getEmployee().getFirstName());
        lblLicense.setText(hospitalEnterprise.getLicence());
        comboBoxHospitalRole.removeAllItems();
        comboBoxHospitalRole.addItem(Organization.Type.DispenserManager.getValue());
        comboBoxHospitalRole.addItem(Organization.Type.Doctor.getValue());
        
        Calendar currentDate = Calendar.getInstance();
        SimpleDateFormat formatter = new SimpleDateFormat("MMM/dd/yyyy");
        String dateNow = formatter.format(currentDate.getTime());
        lblDate.setText(dateNow);

        Refresh();

        
    }
    
    public void Refresh() {
        if (hospitalEnterprise.getLicence().equals(Enterprise.LicNotIssued) || hospitalEnterprise.getLicence().equals(Enterprise.LicUnderProcess)) {
            btnCreate.setEnabled(false);
            txtFirstName.setEditable(false);
            txtLastName.setEditable(false);
            passPassword.setEditable(false);
            txtUsername.setEditable(false);
            comboBoxHospitalRole.setEnabled(false);
        }
        if (hospitalEnterprise.getLicence().equals(Enterprise.LicNotIssued)) {
            btnApplyLicense.setEnabled(true);
        }
        if (hospitalEnterprise.getLicence().equals(Enterprise.LicApproved)) {
            btnApplyLicense.setEnabled(false);
        }
        
        
        for(WorkRequest wr : hospitalEnterprise.getWorkQueue().getWorkRequestQueue())
        {
            AddDrugToYourDirectory w=(AddDrugToYourDirectory)wr;
            if(!(w.getStatus().equals(WorkRequest.Done)))
                        {
                            
                                Object row[] = new Object[2];
                                row[0] = w.getDrugName();
                                row[1]=w;

                                ((DefaultTableModel) tblAddDrug.getModel()).addRow(row);
                            
                        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAddDrug = new javax.swing.JTable();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        passPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboBoxHospitalRole = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AddToDirectory = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        lblAdmin = new javax.swing.JLabel();
        lblLicense = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        btnApplyLicense = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Hospital Admin Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 43, -1, -1));

        tblAddDrug.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug", "wr"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblAddDrug);
        if (tblAddDrug.getColumnModel().getColumnCount() > 0) {
            tblAddDrug.getColumnModel().getColumn(0).setResizable(false);
            tblAddDrug.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 143, 220, 202));

        txtFirstName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 170, 120, -1));

        txtLastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 211, 121, -1));

        txtUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 252, 121, -1));
        add(passPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 290, 121, 23));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Password:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Role:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 336, -1, -1));

        comboBoxHospitalRole.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboBoxHospitalRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboBoxHospitalRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 336, 121, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Username:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 255, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Last Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 214, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("First Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 173, -1, -1));

        AddToDirectory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddToDirectory.setText("Add to Directory");
        AddToDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToDirectoryActionPerformed(evt);
            }
        });
        add(AddToDirectory, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 417, -1, -1));

        btnCreate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 409, 105, 33));
        add(lblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 236, 24));
        add(lblLicense, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 526, 149, 25));
        add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 41, 143, 24));

        btnApplyLicense.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnApplyLicense.setText("Apply for license");
        btnApplyLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyLicenseActionPerformed(evt);
            }
        });
        add(btnApplyLicense, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 526, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("New released Drugs");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void AddToDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToDirectoryActionPerformed
        // TODO add your handling code here:
         int selectedRow = tblAddDrug.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "select row");
            return;
        }

        String d = (String) tblAddDrug.getValueAt(selectedRow, 0);
        AddDrugToYourDirectory wr = (AddDrugToYourDirectory) tblAddDrug.getValueAt(selectedRow, 1);
        hospitalEnterprise.getAllApprovedDrugs().add(d);
        wr.setStatus(WorkRequest.Done);
        
        
    }//GEN-LAST:event_AddToDirectoryActionPerformed

    private void btnApplyLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyLicenseActionPerformed
        // TODO add your handling code here:
        
        ForLicenceByHosWorkRequest work = new ForLicenceByHosWorkRequest();
        work.setHospitalEnterprise(hospitalEnterprise);
        work.setSender(account);
        work.setSendingDate(lblDate.getText());
        work.setStatus(WorkRequest.UnderPro);

        EcoSystem ecoSystem= EcoSystem.getInstance();
        for(Network n:ecoSystem.getNetworkList()){
            for (Enterprise e : n.getEnterprisedirectory().enterpriseDirectory) {
                if ((e.getEnterpriseType().equals(Enterprise.EnterpriseType.License))) {
                    ((LicenseEnterprise) e).getWorkQueue().getWorkRequestQueue().add(work);
                    hospitalEnterprise.setLicence(Enterprise.LicUnderProcess);
                    btnApplyLicense.setEnabled(false);
                }

            }

        }
    }//GEN-LAST:event_btnApplyLicenseActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        
        if (txtFirstName.getText().equals("") || txtLastName.getText().equals("") || txtUsername.getText().equals("") || passPassword.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Some Field is Empty");
            return;
        }
        
        if(!(txtFirstName.getText().trim().matches("^[A-Za-z]+$")))
        {
            JOptionPane.showMessageDialog(null, "Please enter name in proper format");
            return;
        }
        
        if(!(txtLastName.getText().trim().matches("^[A-Za-z]+$")))
        {
            JOptionPane.showMessageDialog(null, "Please enter last name in proper format");
            return;
        }
        
        if(!(txtUsername.getText().trim().matches("^[A-Za-z]+$")))
        {
            JOptionPane.showMessageDialog(null, "Please enter user name in proper format");
            return;
        }

        if (comboBoxHospitalRole.getSelectedItem().toString().equals("Dispense Manager Organization")) {
            Employee dm = hospitalEnterprise.getDispenserManagerOrganization().getEmployeeDirectory().createEmployee(txtFirstName.getText(), txtLastName.getText());
            
            UserAccount user = hospitalEnterprise.getDispenserManagerOrganization().getUserAccountDirectory().createUserAccount(txtUsername.getText(), passPassword.getText(), dm, new DispenserManagerRole());
            JOptionPane.showMessageDialog(null, "Dispenser Manager Created Successfull");
        }

        if (comboBoxHospitalRole.getSelectedItem().toString().equals("Doctor Organization")) {
            Employee d = hospitalEnterprise.getDoctorOrganization().getEmployeeDirectory().createEmployee(txtFirstName.getText(), txtLastName.getText());
            
            UserAccount user = hospitalEnterprise.getDoctorOrganization().getUserAccountDirectory().createUserAccount(txtUsername.getText(), passPassword.getText(), d, new DoctorRole());
            JOptionPane.showMessageDialog(null, "Doctor Created Successfull");
        }
        
        

        txtFirstName.setText("");
        txtLastName.setText("");
        passPassword.setText("");
        txtUsername.setText("");
    }//GEN-LAST:event_btnCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToDirectory;
    private javax.swing.JButton btnApplyLicense;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox<String> comboBoxHospitalRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblLicense;
    private javax.swing.JPasswordField passPassword;
    private javax.swing.JTable tblAddDrug;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
