/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital;

import Business.ClinicalPackage.Treatment;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;

/**
 *
 * @author Rishabh
 */
public class TreatmentDetails extends javax.swing.JPanel {

    /**
     * Creates new form TreatmentDetails
     */
    private JPanel userProcessContainer;
    private Treatment treatment;

    TreatmentDetails(JPanel userProcessContainer, Treatment treatment) {
        initComponents();
        this.treatment=treatment;
        this.userProcessContainer=userProcessContainer;
        
        txtName.setText(treatment.getPatient().getName());
       if(treatment.getPatient().isGender())
       {
        txtGender.setText("Male");   
       }
       if(!treatment.getPatient().isGender()){
         txtGender.setText("Female");  
       }
       txtHeight.setText(String.valueOf(treatment.getPatient().getHeight()));
       txtWeight.setText(String.valueOf(treatment.getPatient().getWeight()));
       
       SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
       System.out.println("Date is : " + formatter.format(treatment.getPatient().getInfectedDate()));
       txtInfectedDate.setText(formatter.format(treatment.getPatient().getInfectedDate()));  
       txtDOB.setText(formatter.format(treatment.getPatient().getDateOfBirth()));
       txtDisease.setText(treatment.getPatient().getDisease().getName());
       txtDosage.setText(String.valueOf(treatment.getDosage()));
       txtDrug.setText(treatment.getDrug().getDrugName());
       txtResponse.setText(String.valueOf(treatment.getResponse()));
       txtSideEffect.setText(String.valueOf(treatment.getSideEffects()));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        txtSideEffect = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtDisease = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtInfectedDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtResponse = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDrug = new javax.swing.JTextField();
        txtDosage = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 284, -1, -1));

        txtSideEffect.setEnabled(false);
        txtSideEffect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSideEffectActionPerformed(evt);
            }
        });
        add(txtSideEffect, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 224, 93, -1));

        jLabel12.setText("Side Effect:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 224, -1, 24));

        jLabel7.setText("Disease:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 301, -1, -1));

        jLabel8.setText("Infected Date:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 339, -1, -1));

        txtName.setEnabled(false);
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 115, 151, -1));

        txtHeight.setEnabled(false);
        add(txtHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 191, 151, -1));

        txtGender.setEnabled(false);
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });
        add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 153, 151, -1));

        txtDisease.setEnabled(false);
        add(txtDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 298, 151, -1));

        jLabel9.setText("Drug:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 116, -1, -1));

        jLabel10.setText("Response:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 189, -1, -1));

        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 118, -1, -1));

        txtWeight.setEnabled(false);
        add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 229, 151, -1));

        jLabel3.setText("Gender:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 156, -1, -1));

        txtDOB.setEnabled(false);
        add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 260, 151, -1));

        jLabel4.setText("Height:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 194, -1, -1));

        jLabel5.setText("Weight:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 232, -1, -1));

        txtInfectedDate.setEnabled(false);
        add(txtInfectedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 336, 151, -1));

        jLabel6.setText("Date of Birth:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 263, -1, -1));

        txtResponse.setEnabled(false);
        txtResponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResponseActionPerformed(evt);
            }
        });
        add(txtResponse, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 186, 93, -1));

        jLabel11.setText("Dosage:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 151, -1, -1));

        jLabel1.setText("Treatment Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 11, 101, 27));

        txtDrug.setEnabled(false);
        add(txtDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 116, 93, -1));

        txtDosage.setEnabled(false);
        txtDosage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDosageActionPerformed(evt);
            }
        });
        add(txtDosage, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 148, 93, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtSideEffectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSideEffectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSideEffectActionPerformed

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void txtResponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResponseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResponseActionPerformed

    private void txtDosageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDosageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDosageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDisease;
    private javax.swing.JTextField txtDosage;
    private javax.swing.JTextField txtDrug;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtInfectedDate;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtResponse;
    private javax.swing.JTextField txtSideEffect;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
