/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital;

import Business.ClinicalPackage.*;
import Business.DrugPackage.*;
import Business.EnterprisePackage.HospitalEnterprise;
import Business.WorkRequestPackage.ForClinicalFromManuToHosp;
import Business.WorkRequestPackage.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Rishabh
 */
public class TreatPatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TreatPatientJPanel
     */
    private JPanel userProcessContainer;
    private Patient patient;
    private DrugDirectory drugDirectory;
    private TreatmentHistory treatmentHistory;
    private HospitalEnterprise hospitalEnterprise;

    TreatPatientJPanel(JPanel userProcessContainer, Patient patient, TreatmentHistory treatmentHistory, HospitalEnterprise hospitalEnterprise) {
       initComponents();
       this.patient=patient;
       this.userProcessContainer=userProcessContainer;
       this.treatmentHistory=treatmentHistory;
       this.hospitalEnterprise= hospitalEnterprise;
       txtName.setText(patient.getName());
       if(patient.isGender())
       {
        txtGender.setText("Male");   
       }
       if(!patient.isGender()){
         txtGender.setText("Female");  
       }
       txtHeight.setText(String.valueOf(patient.getHeight()));
       txtWeight.setText(String.valueOf(patient.getWeight()));
       
       SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
       System.out.println("Date is : " + formatter.format(patient.getInfectedDate()));
       txtInfectedDate.setText(formatter.format(patient.getInfectedDate()));  
       txtDOB.setText(formatter.format(patient.getDateOfBirth()));
       txtDisease.setText(patient.getDisease().getName());
       
       
       
       refresh();
    }
    public void refresh(){
        comboBoxDosage.removeAllItems();
       comboBoxDrug.removeAllItems();
       
           comboBoxDosage.addItem(1);
           comboBoxDosage.addItem(2);
           comboBoxDosage.addItem(3);
           comboBoxDosage.addItem(5);
           comboBoxDosage.addItem(7);
           comboBoxDosage.addItem(10);
       
       
       for(WorkRequest wr1:hospitalEnterprise.getDoctorOrganization().getWorkQueue().getWorkRequestQueue())
       {
           if(wr1 instanceof ForClinicalFromManuToHosp)
           {
            ForClinicalFromManuToHosp wr = (ForClinicalFromManuToHosp)wr1;
            if(!(wr.getStatus().equals("Done")))
            {
                comboBoxDrug.addItem(wr.getDrug());
            }
           }
       }
       
       txtResponse.setText("");
       txtSideEffect.setText("");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtInfectedDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        txtDisease = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        comboBoxDrug = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        txtResponse = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        comboBoxDosage = new javax.swing.JComboBox();
        txtSideEffect = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnTreat = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel2.setText("Name:");

        txtWeight.setEnabled(false);

        jLabel3.setText("Gender:");

        txtDOB.setEnabled(false);

        jLabel4.setText("Height:");

        jLabel5.setText("Weight:");

        txtInfectedDate.setEnabled(false);

        jLabel6.setText("Date of Birth:");

        jLabel7.setText("Disease:");

        jLabel8.setText("Infected Date:");

        txtName.setEnabled(false);

        txtHeight.setEnabled(false);

        jLabel1.setText("Treatment Area");

        txtGender.setEnabled(false);
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });

        txtDisease.setEnabled(false);

        jLabel9.setText("Drug:");

        jLabel10.setText("Response:");

        txtResponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResponseActionPerformed(evt);
            }
        });

        jLabel11.setText("Dosage");

        txtSideEffect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSideEffectActionPerformed(evt);
            }
        });

        jLabel12.setText("Side Effect:");

        btnTreat.setText("Treat");
        btnTreat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreatActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDOB)
                            .addComponent(txtWeight)
                            .addComponent(txtHeight)
                            .addComponent(txtName)
                            .addComponent(txtInfectedDate, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(txtGender)
                            .addComponent(txtDisease))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboBoxDrug, 0, 118, Short.MAX_VALUE)
                                    .addComponent(txtResponse)
                                    .addComponent(comboBoxDosage, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSideEffect, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTreat)))))
                .addContainerGap(346, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(comboBoxDrug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(comboBoxDosage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtResponse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSideEffect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDisease, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtInfectedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTreat)
                    .addComponent(btnBack))
                .addContainerGap(173, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void txtResponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResponseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResponseActionPerformed

    private void txtSideEffectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSideEffectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSideEffectActionPerformed

    private void btnTreatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreatActionPerformed
        
        
        if(!(txtResponse.getText().trim().matches("(?<!\\S)\\d(?![^\\s.,?!])")))
        {
            JOptionPane.showMessageDialog(null, "Please enter response from 1-10");
            return;
        }
        
        if(!(txtSideEffect.getText().trim().matches("(?<!\\S)\\d(?![^\\s.,?!])")))
        {
            JOptionPane.showMessageDialog(null, "Please enter dosage from 1-10");
            return;
        }
        
        Treatment treatment=treatmentHistory.addTreatment();
        treatment.setPatient(patient);
        Drug selectedDrug=(Drug)comboBoxDrug.getSelectedItem();
        treatment.setDrug(selectedDrug);
        treatment.setDosage((int) comboBoxDosage.getSelectedItem());
        treatment.setResponse(Integer.parseInt(txtResponse.getText()));
        treatment.setSideEffects(Integer.parseInt(txtSideEffect.getText()));
        
        refresh();
        
        JOptionPane.showMessageDialog(null, "Treamtment saved successfully");
        

// TODO add your handling code here:
    }//GEN-LAST:event_btnTreatActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] component=userProcessContainer.getComponents();
        Component previous=component[component.length-1];
        DoctorJPanel doctorJPanel=(DoctorJPanel)previous;
        doctorJPanel.refresh();
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnTreat;
    private javax.swing.JComboBox comboBoxDosage;
    private javax.swing.JComboBox comboBoxDrug;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDisease;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtInfectedDate;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtResponse;
    private javax.swing.JTextField txtSideEffect;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
