/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FDA;

import Business.ClinicalPackage.Treatment;
import Business.ClinicalPackage.TreatmentHistory;
import Business.PreClinicalPackage.AnimalTreatment;
import Business.PreClinicalPackage.AnimalTreatmentHistory;
import Business.UserAccountPackage.UserAccount;
import Business.WorkRequestPackage.DrugApprovalFromManuToFDA;
import Business.WorkRequestPackage.WorkRequest;
import UserInterface.Manufacturer.AnimalTreatmentDetails;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Atul
 */
public class CombineTreatmentDetailsJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    WorkRequest workRequest;
    UserAccount userAccount;
    
    
    /**
     * Creates new form CombineTreatmentDetailsJPanel
     */


    CombineTreatmentDetailsJPanel(JPanel userProcessContainer, WorkRequest workRequest, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.workRequest = workRequest;
        this.userAccount = userAccount;
        
        refresh();
        
    }

    public void refresh()
            
    {
        AnimalTreatmentHistory animalTreatmentDetails;
        TreatmentHistory treatmentHistory;
        DrugApprovalFromManuToFDA wr = (DrugApprovalFromManuToFDA)workRequest;
        animalTreatmentDetails = wr.getAnimalTreatmentHistory();
        treatmentHistory = wr.getPatientTreatmentHistory();
        
        for(Treatment t : treatmentHistory.getTreatmentHistory())
        {
            Object row[] = new Object[5];
            row[0] = t;
            row[1] = t.getPatient().getName();
            row[2] = t.getDosage();
            row[3] = t.getResponse();
            row[4] = t.getSideEffects();

            ((DefaultTableModel) tblClinicalReport.getModel()).addRow(row);
        }
        
        for(AnimalTreatment t:animalTreatmentDetails.getAnimalTreatmentHistory())
            {
                Object row[] = new Object[5];
                row[0] = t.getDrug();
                row[1] = t.getAnimal().getAnimalType();
                row[2] = t.getDosage();
                row[3] = t.getResponse();
                row[4] = t.getSideEffect();

                ((DefaultTableModel) tblPreclinicalReport.getModel()).addRow(row);
            }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPreclinicalReport = new javax.swing.JTable();
        btnApproveDrug = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClinicalReport = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("Preclinical");

        tblPreclinicalReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPreclinicalReport);

        btnApproveDrug.setText("Approve Drug");
        btnApproveDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveDrugActionPerformed(evt);
            }
        });

        tblClinicalReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblClinicalReport);

        jLabel2.setText("Hospital");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 811, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(183, 183, 183)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(btnApproveDrug)))
                    .addGap(183, 183, 183)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(72, 72, 72)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnApproveDrug)
                    .addContainerGap(87, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveDrugActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnApproveDrugActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApproveDrug;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblClinicalReport;
    private javax.swing.JTable tblPreclinicalReport;
    // End of variables declaration//GEN-END:variables
}
