/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FDA;

import Business.EnterprisePackage.Enterprise;
import Business.EnterprisePackage.FDAEnterprise;
import Business.UserAccountPackage.UserAccount;
import Business.WorkRequestPackage.DrugApprovalFromManuToFDA;
import Business.WorkRequestPackage.ForLicenceByManuWorkRequest;
import Business.WorkRequestPackage.WorkRequest;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Atul
 */
public class FDAManagerJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    FDAEnterprise fDAEnterprise;
    UserAccount userAccount;
    /**
     * Creates new form FDAManagerJPanel
     */
    public FDAManagerJPanel(JPanel j, Enterprise e, UserAccount u) {
        initComponents();
        userProcessContainer = j;
        fDAEnterprise = (FDAEnterprise) e;
        userAccount = u;

        Calendar currentDate = Calendar.getInstance();
        SimpleDateFormat formatter = new SimpleDateFormat("MMM/dd/yyyy");
        String dateNow = formatter.format(currentDate.getTime());
        lblDate.setText(dateNow);

        lblName.setText("Licence Manager Name is : " + u.getEmployee().getFirstName());

        int rowCount = requestForLicenceJTable.getRowCount();

        for (int i = rowCount - 1; i >= 0; i--) {
            ((DefaultTableModel) requestForLicenceJTable.getModel()).removeRow(i);
        }

        Refresh();
    }
    
    public void Refresh() {
        int rowCount = requestForLicenceJTable.getRowCount();

        for (int i = rowCount - 1; i >= 0; i--) {
            ((DefaultTableModel) requestForLicenceJTable.getModel()).removeRow(i);
        }

        for (WorkRequest wr : fDAEnterprise.getFdaOrganization().getWorkQueue().getWorkRequestQueue()) {

            if(wr instanceof ForLicenceByManuWorkRequest)
            {
                Object row[] = new Object[6];
                row[0] = (ForLicenceByManuWorkRequest) wr;
                row[1] = wr.getSender();
                row[2] = wr.getReceiver();
                row[3] = wr.getStatus();
                row[4] = wr.getSendingDate();
                row[5] = wr.getReceivingDate();

                ((DefaultTableModel) requestForLicenceJTable.getModel()).addRow(row);
            }
            
            else if(wr instanceof DrugApprovalFromManuToFDA)
            {
                Object row[] = new Object[6];
                row[0] = (DrugApprovalFromManuToFDA) wr;
                row[1] = ((DrugApprovalFromManuToFDA) wr).getDrug();
                row[2] = wr.getStatus();
                row[3] = wr.getStatus();
                row[4] = wr.getSendingDate();
                row[5] = wr.getReceivingDate();

                ((DefaultTableModel) requestForDrugApproval.getModel()).addRow(row);
            }
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestForLicenceJTable = new javax.swing.JTable();
        btnApprove = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        requestForDrugApproval = new javax.swing.JTable();
        btnDetails = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FDA Manager Workarea");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Request For Licence By Manufacturers ");

        requestForLicenceJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Manufacturer Name", "Sender", "Receiver", "Status", "SendingDate", "Receing Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(requestForLicenceJTable);
        if (requestForLicenceJTable.getColumnModel().getColumnCount() > 0) {
            requestForLicenceJTable.getColumnModel().getColumn(0).setResizable(false);
            requestForLicenceJTable.getColumnModel().getColumn(1).setResizable(false);
            requestForLicenceJTable.getColumnModel().getColumn(2).setResizable(false);
            requestForLicenceJTable.getColumnModel().getColumn(3).setResizable(false);
            requestForLicenceJTable.getColumnModel().getColumn(4).setResizable(false);
            requestForLicenceJTable.getColumnModel().getColumn(5).setResizable(false);
        }

        btnApprove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Request For Drug Approval By Manufacturers ");

        requestForDrugApproval.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Manufacturer Name", "Sender", "Receiver", "Status", "SendingDate", "Receing Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(requestForDrugApproval);
        if (requestForDrugApproval.getColumnModel().getColumnCount() > 0) {
            requestForDrugApproval.getColumnModel().getColumn(0).setResizable(false);
            requestForDrugApproval.getColumnModel().getColumn(1).setResizable(false);
            requestForDrugApproval.getColumnModel().getColumn(2).setResizable(false);
            requestForDrugApproval.getColumnModel().getColumn(3).setResizable(false);
            requestForDrugApproval.getColumnModel().getColumn(4).setResizable(false);
            requestForDrugApproval.getColumnModel().getColumn(5).setResizable(false);
        }

        btnDetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDetails.setText("View Details");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnApprove))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDetails))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(454, 793, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnApprove)
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDetails)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed

        int selectedRow = requestForLicenceJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select Row to Approve licence");
            return;
        }

        WorkRequest workRequest = (WorkRequest) requestForLicenceJTable.getValueAt(selectedRow, 0);

        if (workRequest.getStatus().equals(WorkRequest.Done)) {
            JOptionPane.showMessageDialog(null, "Licence Already Approved");
            return;
        }

        ((ForLicenceByManuWorkRequest) workRequest).getManufacturerEnterprise().setLicence(Enterprise.LicApproved);
        workRequest.setStatus(WorkRequest.Done);
        workRequest.setReceiver(userAccount);
        workRequest.setReceivingDate(lblDate.getText());
        Refresh();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        // TODO add your handling code here:

       int selectedRow = requestForDrugApproval.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select Row to View Details");
            return;
        }

        WorkRequest workRequest = (WorkRequest) requestForDrugApproval.getValueAt(selectedRow, 0);

        if (workRequest.getStatus().equals(WorkRequest.Done)) {
            JOptionPane.showMessageDialog(null, "Drug Already Approved");
            return;
        }
        
        ApproveDrugOfManufacturer panel = new ApproveDrugOfManufacturer(userProcessContainer, workRequest, userAccount);
        userProcessContainer.add("viewDetails", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
        
        


        
        
    }//GEN-LAST:event_btnDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblName;
    private javax.swing.JTable requestForDrugApproval;
    private javax.swing.JTable requestForLicenceJTable;
    // End of variables declaration//GEN-END:variables
}
