/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdmin;

import Business.EcoSystem;
import Business.EmployeePackage.Employee;
import Business.EnterprisePackage.Enterprise;
import Business.EnterprisePackage.FDAEnterprise;
import Business.EnterprisePackage.HospitalEnterprise;
import Business.EnterprisePackage.LicenseEnterprise;
import Business.EnterprisePackage.ManufacturerEnterprise;
import Business.EnterprisePackage.WarehouseEnterprise;
import Business.NetworkPackage.Network;
import Business.OrganizationPackage.DispenserManagerOrganization;
import Business.OrganizationPackage.DoctorOrganization;
import Business.OrganizationPackage.DrugManagerOrganization;
import Business.OrganizationPackage.FDAOrganization;
import Business.OrganizationPackage.InventoryManagerOrganization;
import Business.OrganizationPackage.LicenseManagerOrganization;
import Business.OrganizationPackage.PreClinicalTesterOrgnization;
import Business.OrganizationPackage.SalesManagerOrganization;
import Business.OrganizationPackage.WarehouseManagerOrganization;
import Business.RolePackage.FDAAdminRole;
import Business.RolePackage.HospitalAdminRole;
import Business.RolePackage.LicenseAdminRole;
import Business.RolePackage.ManufactureAdminRole;
import Business.RolePackage.SystemAdminRole;
import Business.RolePackage.WarehouseAdminRole;
import Business.UserAccountPackage.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Atul
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageEnterpriseAdminJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.system = system;

        populateTable();
        populateNetworkComboBox();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) enterpriseJTable.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterprisedirectory().getEnterpriseDirectory()) {
                for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserAccountList()) {
                    Object[] row = new Object[3];
                    row[0] = enterprise.getOrganizationName();
                    row[1] = network.getName();
                    row[2] = userAccount.getUsername();

                    model.addRow(row);
                }
            }
        }
    }

    private void populateNetworkComboBox(){
        cmbxNetwork.removeAllItems();
        
        for (Network network : system.getNetworkList()){
            cmbxNetwork.addItem(network);
        }
    }
    
    private void populateEnterpriseComboBox(Network network){
        cmbxEnterprise.removeAllItems();
        
        for (Enterprise enterprise : network.getEnterprisedirectory().getEnterpriseDirectory()){
            cmbxEnterprise.addItem(enterprise);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cmbxNetwork = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbxEnterprise = new javax.swing.JComboBox();
        btnSubmit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        backJButton = new javax.swing.JButton();
        txtLastName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Network", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enterpriseJTable);
        if (enterpriseJTable.getColumnModel().getColumnCount() > 0) {
            enterpriseJTable.getColumnModel().getColumn(0).setResizable(false);
            enterpriseJTable.getColumnModel().getColumn(1).setResizable(false);
            enterpriseJTable.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 58, 552, 95));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Network");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        cmbxNetwork.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbxNetwork.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbxNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxNetworkActionPerformed(evt);
            }
        });
        add(cmbxNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 136, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Username");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        txtUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 136, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Enterprise");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        cmbxEnterprise.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbxEnterprise.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbxEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 136, -1));

        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Password");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        txtFirstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 136, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("First Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 134, -1));

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        txtLastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 136, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Last Name:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("System Admin Work Area");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cmbxNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxNetworkActionPerformed

        Network network = (Network) cmbxNetwork.getSelectedItem();
        if (network != null){
            populateEnterpriseComboBox(network);
        }
        
        
    }//GEN-LAST:event_cmbxNetworkActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        
        Network networkSelected = null;
        if (txtFirstName.getText().equals("") || txtLastName.getText().equals("") || txtUserName.getText().equals("") || txtPassword.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Some Field is Empty");
            return;
        }

        for(Network n:system.getNetworkList())
        {
            if(n.getName().equals(cmbxNetwork.getSelectedItem().toString()))
                networkSelected = n;
        }
        
        for (Enterprise enterprise : networkSelected.getEnterprisedirectory().getEnterpriseDirectory()) {
            for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserAccountList()) {
                if (txtUserName.getText().equals(userAccount.getUsername())) {
                    JOptionPane.showMessageDialog(null, "UserName already Exist");
                    return;
                }
            }

            if (enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.FDA)) {
                FDAOrganization o = ((FDAEnterprise) enterprise).getFdaOrganization();

                for (UserAccount userAccount : o.getUserAccountDirectory().getUserAccountList()) {
                    if (txtUserName.getText().equals(userAccount.getUsername())) {
                        JOptionPane.showMessageDialog(null, "UserName already Exist");
                        return;
                    }

                }
            }

            if (enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Manufacturer)) {
                SalesManagerOrganization o = ((ManufacturerEnterprise) enterprise).getSalesManagerOrganization();

                for (UserAccount userAccount : o.getUserAccountDirectory().getUserAccountList()) {
                    if (txtUserName.getText().equals(userAccount.getUsername())) {
                        JOptionPane.showMessageDialog(null, "UserName already Exist");
                        return;
                    }

                }
            }
            
            if (enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Manufacturer)) {
                DrugManagerOrganization o = ((ManufacturerEnterprise) enterprise).getDrugManagerOrganization();

                for (UserAccount userAccount : o.getUserAccountDirectory().getUserAccountList()) {
                    if (txtUserName.getText().equals(userAccount.getUsername())) {
                        JOptionPane.showMessageDialog(null, "UserName already Exist");
                        return;
                    }

                }
            }
            
            if (enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Manufacturer)) {
                PreClinicalTesterOrgnization o = ((ManufacturerEnterprise) enterprise).getPreClinicalTesterOrgnization();

                for (UserAccount userAccount : o.getUserAccountDirectory().getUserAccountList()) {
                    if (txtUserName.getText().equals(userAccount.getUsername())) {
                        JOptionPane.showMessageDialog(null, "UserName already Exist");
                        return;
                    }

                }
            }
            
            if (enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Hospital)) {
                DispenserManagerOrganization o = ((HospitalEnterprise) enterprise).getDispenserManagerOrganization();

                for (UserAccount userAccount : o.getUserAccountDirectory().getUserAccountList()) {
                    if (txtUserName.getText().equals(userAccount.getUsername())) {
                        JOptionPane.showMessageDialog(null, "UserName already Exist");
                        return;
                    }

                }
            }
            
            if (enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Hospital)) {
                DoctorOrganization o = ((HospitalEnterprise) enterprise).getDoctorOrganization();

                for (UserAccount userAccount : o.getUserAccountDirectory().getUserAccountList()) {
                    if (txtUserName.getText().equals(userAccount.getUsername())) {
                        JOptionPane.showMessageDialog(null, "UserName already Exist");
                        return;
                    }

                }
            }
            
            if (enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.License)) {
                LicenseManagerOrganization o = ((LicenseEnterprise) enterprise).getLicenseManagerOrganization();

                for (UserAccount userAccount : o.getUserAccountDirectory().getUserAccountList()) {
                    if (txtUserName.getText().equals(userAccount.getUsername())) {
                        JOptionPane.showMessageDialog(null, "UserName already Exist");
                        return;
                    }

                }
            }
            
            if (enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Warehouse)) {
                WarehouseManagerOrganization o = ((WarehouseEnterprise) enterprise).getWarehouseManagerOrganization();

                for (UserAccount userAccount : o.getUserAccountDirectory().getUserAccountList()) {
                    if (txtUserName.getText().equals(userAccount.getUsername())) {
                        JOptionPane.showMessageDialog(null, "UserName already Exist");
                        return;
                    }

                }
            }
            
            if (enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Warehouse)) {
                InventoryManagerOrganization o = ((WarehouseEnterprise) enterprise).getInventoryManagerOrganization();

                for (UserAccount userAccount : o.getUserAccountDirectory().getUserAccountList()) {
                    if (txtUserName.getText().equals(userAccount.getUsername())) {
                        JOptionPane.showMessageDialog(null, "UserName already Exist");
                        return;
                    }

                }
            }
        }
        
        
        if(cmbxEnterprise.getSelectedItem() instanceof FDAEnterprise)
        {
            for(Enterprise e : networkSelected.getEnterprisedirectory().getEnterpriseDirectory())
            {
                if(e.getEnterpriseType().getValue().equals("FDA"))
                {
                    Employee employee = e.getEmployeeDirectory().createEmployee(txtFirstName.getText(), txtLastName.getText());
                    UserAccount userAccount= e.getUserAccountDirectory().createUserAccount(txtUserName.getText(), txtPassword.getText(), employee, new FDAAdminRole());
                }
            }
        }

          if(cmbxEnterprise.getSelectedItem() instanceof ManufacturerEnterprise )
        {
            for(Enterprise e : networkSelected.getEnterprisedirectory().getEnterpriseDirectory())
            {
                if(e.getEnterpriseType().getValue().equals("Manufacturer"))
                {
                    Employee employee = e.getEmployeeDirectory().createEmployee(txtFirstName.getText(), txtLastName.getText());
                    UserAccount userAccount= e.getUserAccountDirectory().createUserAccount(txtUserName.getText(), txtPassword.getText(), employee, new ManufactureAdminRole());
                }
            }
        }
          
          if(cmbxEnterprise.getSelectedItem() instanceof HospitalEnterprise)
        {
            for(Enterprise e : networkSelected.getEnterprisedirectory().getEnterpriseDirectory())
            {
                if(e.getEnterpriseType().getValue().equals("Hospital"))
                {
                    Employee employee = e.getEmployeeDirectory().createEmployee(txtFirstName.getText(), txtLastName.getText());
                    UserAccount userAccount= e.getUserAccountDirectory().createUserAccount(txtUserName.getText(), txtPassword.getText(), employee, new HospitalAdminRole());
                }
            }
        }
          if(cmbxEnterprise.getSelectedItem() instanceof WarehouseEnterprise)
        {
            for(Enterprise e : networkSelected.getEnterprisedirectory().getEnterpriseDirectory())
            {
                if(e.getEnterpriseType().getValue().equals("Warehouse"))
                {
                    Employee employee = e.getEmployeeDirectory().createEmployee(txtFirstName.getText(), txtLastName.getText());
                    UserAccount userAccount= e.getUserAccountDirectory().createUserAccount(txtUserName.getText(), txtPassword.getText(), employee, new WarehouseAdminRole());
                }
            }
        }
          if(cmbxEnterprise.getSelectedItem() instanceof LicenseEnterprise)
        {
            for(Enterprise e : networkSelected.getEnterprisedirectory().getEnterpriseDirectory())
            {
                if(e.getEnterpriseType().getValue().equals("License"))
                {
                    Employee employee = e.getEmployeeDirectory().createEmployee(txtFirstName.getText(), txtLastName.getText());
                    UserAccount userAccount= e.getUserAccountDirectory().createUserAccount(txtUserName.getText(), txtPassword.getText(), employee, new LicenseAdminRole());
                }
            }
        }
//
        txtFirstName.setText("");
        txtLastName.setText("");
        txtUserName.setText("");
        txtPassword.setText("");
        

        populateTable();
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
         Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
//        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox cmbxEnterprise;
    private javax.swing.JComboBox cmbxNetwork;
    private javax.swing.JTable enterpriseJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
